"use client";

import { useEffect, useState, Suspense } from "react";
import { useRouter, useParams, useSearchParams } from "next/navigation";
import { ArrowLeft, Check, Smartphone, User } from "lucide-react";
import { motion } from "framer-motion";


function GuestPaySplitContent() {
    const router = useRouter();
    const params = useParams();
    const searchParams = useSearchParams();
    const id = params.id as string;

    // If email is present (e.g. from old link), use it. Else, we let user pick.
    const [email, setEmail] = useState<string | null>(searchParams.get('email'));

    const [isLoading, setIsLoading] = useState(false);
    const [amount, setAmount] = useState<number | null>(null);
    const [alreadyPaid, setAlreadyPaid] = useState(false);
    const [groupMembers, setGroupMembers] = useState<any[]>([]);
    const [selectedMemberId, setSelectedMemberId] = useState<string | null>(null);

    // Fetch Group Data
    useEffect(() => {
        fetch(`${(process.env.NEXT_PUBLIC_API_URL || "").replace(/\/$/, "")}/api/group-orders/${id}`)
            .then(res => res.json())
            .then(data => {
                if (data.group_order_members) {
                    setGroupMembers(data.group_order_members);

                    // If we have an email/member selected via URL or previous selection
                    if (email) {
                        const me = data.group_order_members.find((m: any) => m.email === email);
                        if (me) {
                            setSelectedMemberId(me.id);
                            setAmount(me.share_amount);
                            setAlreadyPaid(me.status === 'paid');
                        }
                    }
                }
            })
            .catch(err => console.error(err));
    }, [id, email]);

    const handleSelectMember = (member: any) => {
        setEmail(member.email);
        setSelectedMemberId(member.id);
        setAmount(member.share_amount);
        setAlreadyPaid(member.status === 'paid');
    };

    const handlePay = async () => {
        if (!email) return;

        setIsLoading(true);
        try {
            const res = await fetch(`${(process.env.NEXT_PUBLIC_API_URL || "").replace(/\/$/, "")}/api/group-orders/${id}/pay`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    email: email, // We prefer ID but backend uses Email for lookup currently. 
                    // To be safe with "Membro 1" duplicates if we had them (unique constraint?), passing ID would be better.
                    // But our backend lookups by (group_id, email). "Membro 1" is unique per group conceptually if generated by loop.
                    payment_method: 'pix_mock'
                })
            });
            const data = await res.json();

            if (data.success) {
                if (!localStorage.getItem('ezdrink_token')) {
                    localStorage.setItem('ezdrink_guest_email', email || '');
                }
                router.push(`/split/${id}`);
            } else {
                alert("Erro: " + data.error);
            }
        } catch (e) {
            alert("Erro de conexão");
        } finally {
            setIsLoading(false);
        }
    };

    if (!groupMembers.length) return <div className="min-h-screen flex items-center justify-center font-bold">Carregando GRUPO...</div>;

    // SCENARIO 1: Slot Selection (No Email Selected yet)
    if (!email) {
        return (
            <div className="min-h-screen bg-[#f4f4f5] font-sans flex flex-col p-6">
                <header className="flex items-center mb-8">
                    <button onClick={() => router.push('/')} className="p-2 bg-white rounded-full">
                        <ArrowLeft className="w-6 h-6" />
                    </button>
                    <h1 className="text-xl font-bold ml-4">Escolha sua Cota</h1>
                </header>

                <div className="space-y-4">
                    {groupMembers.map((m, idx) => (
                        <button
                            key={m.id}
                            disabled={m.status === 'paid'}
                            onClick={() => handleSelectMember(m)}
                            className={`w-full p-6 rounded-2xl flex items-center justify-between shadow-sm border transaction-all
                                ${m.status === 'paid' ? 'bg-gray-100 border-gray-200 opacity-60' : 'bg-white border-gray-100 hover:border-black'}
                            `}
                        >
                            <div className="flex items-center gap-4">
                                <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold ${m.status === 'paid' ? 'bg-gray-200 text-gray-500' : 'bg-primary/10 text-primary'}`}>
                                    {idx + 1}
                                </div>
                                <div className="text-left">
                                    <p className="font-bold text-gray-800">{m.email.includes('@') ? m.email.split('@')[0] : `Pessoa ${idx + 1}`}</p>
                                    <p className="text-sm text-gray-500">R$ {m.share_amount.toFixed(2)}</p>
                                </div>
                            </div>

                            {m.status === 'paid' ? (
                                <span className="text-xs font-bold bg-green-100 text-green-700 px-3 py-1 rounded-full">PAGO</span>
                            ) : (
                                <span className="text-xs font-bold bg-black text-white px-3 py-1 rounded-full">PAGAR</span>
                            )}
                        </button>
                    ))}
                </div>
            </div>
        );
    }

    // SCENARIO 2: Ready to Pay (Email Selected)
    return (
        <div className="fixed inset-0 bg-primary font-sans flex flex-col justify-end">
            <div className="bg-[#f4f4f5] w-full h-[calc(100vh-24px)] rounded-t-[40px] shadow-2xl overflow-hidden flex flex-col">
                <header className="px-6 py-6 flex items-center justify-between sticky top-0 z-10 bg-[#f4f4f5]/90 backdrop-blur-md">
                    <button onClick={() => setEmail(null)} className="p-2 hover:bg-black/5 rounded-full">
                        <ArrowLeft className="w-6 h-6" />
                    </button>
                    <h1 className="text-xl font-bold">Pagamento</h1>
                    <div className="w-10" />
                </header>

                <main className="flex-1 px-6 flex flex-col items-center justify-center">

                    <div className="w-24 h-24 bg-white rounded-full flex items-center justify-center shadow-sm mb-6">
                        <User className="w-10 h-10 text-primary" />
                    </div>

                    <h2 className="text-2xl font-bold text-center mb-2">
                        {email.includes('@') ? email.split('@')[0] : email}
                    </h2>
                    <p className="text-gray-500 text-center mb-8 max-w-xs">
                        Confirme o valor da sua parte:
                    </p>

                    <h1 className="text-5xl font-extrabold text-primary mb-8 tracking-tight">
                        R$ {amount?.toFixed(2)}
                    </h1>

                    {alreadyPaid ? (
                        <button
                            onClick={() => router.push(`/split/${id}`)}
                            className="w-full bg-green-600 text-white font-bold text-lg py-4 rounded-xl shadow-md"
                        >
                            Já pago! Ver Grupo
                        </button>
                    ) : (
                        <button
                            onClick={handlePay}
                            disabled={isLoading}
                            className="w-full bg-primary text-primary-foreground font-bold text-lg py-4 rounded-xl hover:brightness-110 transition-all shadow-md flex items-center justify-center gap-2"
                        >
                            {isLoading ? "Processando..." : (
                                <>
                                    <Smartphone className="w-5 h-5" />
                                    Pagar com Pix
                                </>
                            )}
                        </button>
                    )}

                    <p className="mt-4 text-xs text-center text-gray-400">
                        Ambiente Seguro EzDrink
                    </p>
                </main>
            </div>
        </div>
    );
}

export default function GuestPaySplitPage() {
    return (
        <Suspense fallback={
            <div className="fixed inset-0 bg-[#f4f4f5] flex items-center justify-center">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
            </div>
        }>
            <GuestPaySplitContent />
        </Suspense>
    );
}
