-- Tabela de Usuários (Mantendo a lógica customizada por enquanto)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, -- Continuaremos usando hash manual/simples por enquanto
    phone TEXT,
    cpf TEXT,
    user_type TEXT DEFAULT 'customer', -- 'customer', 'admin', 'establishment', 'user' (staff)
    establishment_role TEXT, -- 'waiter', 'bartender', 'manager'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Categorias
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL
);

-- Tabela de Produtos
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    description TEXT,
    image_url TEXT,
    category_id BIGINT REFERENCES public.categories(id),
    is_popular BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Pedidos
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL, -- Relacionamento lógico via email por enquanto
    total_amount DECIMAL(10,2) NOT NULL,
    payment_method TEXT NOT NULL, -- 'pix', 'credit_card', 'balance', 'apple_pay', 'cash'
    status TEXT DEFAULT 'aguardando_pagamento', -- 'aguardando_pagamento', 'confirmado', 'entregue', 'cancelado'
    ticket_code TEXT,
    stripe_payment_intent_id TEXT,
    pix_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Itens do Pedido
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    total_price DECIMAL(10,2) NOT NULL
);

-- Inserir Dados Iniciais (Seed)
INSERT INTO public.categories (name, slug) VALUES 
('Drinks', 'drinks'),
('Cervejas', 'beers'),
('Combos', 'combos')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, price, is_popular, image_url, category_id) VALUES
('Gin Tônica', 25.00, TRUE, '/uploads/gin.jpg', 1),
('Vodka com Energético', 22.00, TRUE, '/uploads/vodka.jpg', 1),
('Combo Absolut', 150.00, FALSE, '/uploads/combo.jpg', 3)
ON CONFLICT DO NOTHING;

-- Criar Admin Padrão
INSERT INTO public.users (full_name, email, password, user_type)
VALUES ('Admin', 'admin@ezdrink.com', 'admin123', 'admin')
ON CONFLICT (email) DO NOTHING;
