-- Safe Migration Script for Categories
-- Run this in Supabase SQL Editor

-- 1. Create table only if it doesn't exist (Standard fix)
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    order_index integer default 0,
    icon text
);

-- 2. Enable RLS (Safe to run multiple times)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing policies to avoid "policy already exists" errors
DROP POLICY IF EXISTS "Allow public read access" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.categories;

-- 4. Re-create policies
CREATE POLICY "Allow public read access"
  ON public.categories FOR SELECT
  USING ( true );

CREATE POLICY "Allow authenticated insert"
  ON public.categories FOR INSERT
  WITH CHECK ( auth.role() = 'authenticated' );

CREATE POLICY "Allow authenticated update"
  ON public.categories FOR UPDATE
  USING ( auth.role() = 'authenticated' );

CREATE POLICY "Allow authenticated delete"
  ON public.categories FOR DELETE
  USING ( auth.role() = 'authenticated' );
