-- Create Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  order_index integer default 0,
  icon text
);

-- Enable RLS
alter table public.categories enable row level security;

-- Policies (Public Read, Admin Write)
create policy "Allow public read access"
  on public.categories for select
  using ( true );

create policy "Allow authenticated insert"
  on public.categories for insert
  with check ( auth.role() = 'authenticated' );

create policy "Allow authenticated update"
  on public.categories for update
  using ( auth.role() = 'authenticated' );

create policy "Allow authenticated delete"
  on public.categories for delete
  using ( auth.role() = 'authenticated' );
