-- NEW TABLE: menu_categories
-- Replacing 'categories' to avoid RLS/Cache issues.

-- 1. Create the table
CREATE TABLE public.menu_categories (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    icon text,
    order_index integer default 0
);

-- 2. Enable RLS
ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;

-- 3. Create Clean Policies

-- READ: Everyone (Public + Auth) can read categories (for the menu)
CREATE POLICY "Public Read Access"
ON public.menu_categories FOR SELECT
USING ( true );

-- WRITE: Only Authenticated Users can Insert/Update/Delete (Admin)
CREATE POLICY "Authenticated Insert"
ON public.menu_categories FOR INSERT
WITH CHECK ( auth.role() = 'authenticated' );

CREATE POLICY "Authenticated Update"
ON public.menu_categories FOR UPDATE
USING ( auth.role() = 'authenticated' );

CREATE POLICY "Authenticated Delete"
ON public.menu_categories FOR DELETE
USING ( auth.role() = 'authenticated' );
